# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-15 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='jumboImg4',
        ),
    ]
