# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-07 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20161105_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizacion',
            name='localizacion_maps',
            field=models.TextField(blank=True),
        ),
    ]
