# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-07 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_localizacion_localizacion_maps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listanovios',
            name='foto',
        ),
        migrations.DeleteModel(
            name='ListaNovios',
        ),
    ]
