# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-07 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0028_merge'),
        ('wagtailimages', '0012_copy_image_permissions_to_collections'),
        ('home', '0010_listanovios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acomodaciones',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('mensajeBreve', models.TextField()),
                ('mensajeHoteles', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('mensajeRestaurants', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('mensajeTurismo', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('imagenFooter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('imagenHeader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='confirmacion',
            name='imagenFooter',
        ),
        migrations.RemoveField(
            model_name='confirmacion',
            name='imagenHeader',
        ),
        migrations.RemoveField(
            model_name='confirmacion',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='Confirmacion',
        ),
    ]
